export const TRAIL_NAME_SLUGS = {
  apex: 'apex',
  centennialCone: 'centennial-cone',
  chimneyGulch: 'chimney-gulch',
  chimPex: 'chimpex',
  cubCreek: 'cub-creek',
  dakotaRidge: 'dakota-ridge',
  deerCreekCanyon: 'deer-creek-canyon',
  elkMeadowBergan: 'elk-meadow-bergan',
  floydHill: 'floyd-hill',
  greenMountain: 'green-mountain',
  lairOfTheBear: 'lair-of-the-bear',
  marylandMountain: 'maryland-mountain',
  goldenGateMountainLion: 'golden-gate-mountain-lion',
  mountFalcon: 'mount-falcon',
  goldenGateMuleDeer: 'golden-gate-mule-deer',
  northTableMountain: 'north-table-mountain',
  threeSisters: 'three-sisters',
  virginiaCanyon: 'virginia-canyon',
  warrenGulch: 'warren-gulch',
  whiteRanch: 'white-ranch',
};

export const TRAIL_NAMES = {
  apex: 'Apex',
  centennialCone: 'Centennial Cone',
  chimneyGulch: 'Chimney Gulch',
  chimPex: 'Chimpex',
  cubCreek: 'Cub Creek',
  dakotaRidge: 'Dakota Ridge',
  deerCreekCanyon: 'Deer Creek Canyon',
  elkMeadowBergan: 'Elk Meadow Bergan',
  floydHill: 'Floyd Hill',
  greenMountain: 'Green Mountain',
  lairOfTheBear: 'Lair Of The Bear',
  marylandMountain: 'Maryland Mountain',
  goldenGateMountainLion: 'Golden Gate Mountain Lion',
  mountFalcon: 'Mount Falcon',
  goldenGateMuleDeer: 'Golden Gate Mule Deer',
  northTableMountain: 'North Table Mountain',
  threeSisters: 'Didesse Alderfer Three Sisters',
  virginiaCanyon: 'Virginia Canyon',
  warrenGulch: 'Warren Gulch',
  whiteRanch: 'White Ranch',
};

export const RIDE_SCHEDULE = [
  TRAIL_NAMES.dakotaRidge,
  TRAIL_NAMES.northTableMountain,
  TRAIL_NAMES.lairOfTheBear,
  TRAIL_NAMES.floydHill,
  TRAIL_NAMES.whiteRanch,
  TRAIL_NAMES.threeSisters,
  TRAIL_NAMES.whiteRanch,
  TRAIL_NAMES.floydHill,
  TRAIL_NAMES.mountFalcon,
  TRAIL_NAMES.marylandMountain,
  TRAIL_NAMES.chimPex,
  TRAIL_NAMES.elkMeadowBergan,
  TRAIL_NAMES.floydHill,
  TRAIL_NAMES.warrenGulch,
  TRAIL_NAMES.cubCreek,
  TRAIL_NAMES.deerCreekCanyon,
  TRAIL_NAMES.goldenGateMuleDeer,
  TRAIL_NAMES.apex,
  TRAIL_NAMES.marylandMountain,
  TRAIL_NAMES.virginiaCanyon,
  TRAIL_NAMES.goldenGateMountainLion,
  TRAIL_NAMES.floydHill,
  TRAIL_NAMES.whiteRanch,
  TRAIL_NAMES.lairOfTheBear,
  TRAIL_NAMES.dakotaRidge,
  TRAIL_NAMES.elkMeadowBergan,
  TRAIL_NAMES.chimPex,
  TRAIL_NAMES.marylandMountain,
  TRAIL_NAMES.virginiaCanyon,
  TRAIL_NAMES.threeSisters,
  TRAIL_NAMES.whiteRanch,
  TRAIL_NAMES.apex,
  TRAIL_NAMES.lairOfTheBear,
  TRAIL_NAMES.northTableMountain,
  TRAIL_NAMES.greenMountain,
];
