export const TRAIL_NAME_SLUGS = {
  apex: 'apex',
  centennialCone: 'centennial-cone',
  chimneyGulch: 'chimney-gulch',
  chimPex: 'chimpex',
  cubCreek: 'cub-creek',
  dakotaRidge: 'dakota-ridge',
  deerCreekCanyon: 'deer-creek-canyon',
  elkMeadowBergan: 'elk-meadow-bergan',
  floydHill: 'floyd-hill',
  greenMountain: 'green-mountain',
  lairOfTheBear: 'lair-of-the-bear',
  marylandMountain: 'maryland-mountain',
  goldenGateMountainLion: 'golden-gate-mountain-lion',
  mountFalcon: 'mount-falcon',
  goldenGateMuleDeer: 'golden-gate-mule-deer',
  northTableMountain: 'north-table-mountain',
  threeSisters: 'three-sisters',
  virginiaCanyon: 'virginia-canyon',
  warrenGulch: 'warren-gulch',
  whiteRanch: 'white-ranch',
};

export const TRAIL_NAMES = {
  apex: 'Apex',
  centennialCone: 'Centennial Cone',
  chimneyGulch: 'Chimney Gulch',
  chimPex: 'Chimpex',
  cubCreek: 'Cub Creek',
  dakotaRidge: 'Dakota Ridge',
  deerCreekCanyon: 'Deer Creek Canyon',
  elkMeadowBergan: 'Elk Meadow Bergan',
  floydHill: 'Floyd Hill',
  greenMountain: 'Green Mountain',
  lairOfTheBear: 'Lair Of The Bear',
  marylandMountain: 'Maryland Mountain',
  goldenGateMountainLion: 'Golden Gate Mountain Lion',
  mountFalcon: 'Mount Falcon',
  goldenGateMuleDeer: 'Golden Gate Mule Deer',
  northTableMountain: 'North Table Mountain',
  threeSisters: 'Didesse Alderfer Three Sisters',
  virginiaCanyon: 'Virginia Canyon',
  warrenGulch: 'Warren Gulch',
  whiteRanch: 'White Ranch',
};

export const RIDE_SCHEDULE = [
  { trail: TRAIL_NAMES.dakotaRidge, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.northTableMountain, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.whiteRanch, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.apex, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.lairOfTheBear, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.floydHill, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.mountFalcon, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.threeSisters, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.whiteRanch, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.chimPex, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.virginiaCanyon, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.floydHill, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.whiteRanch, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.apex, startTime: '5:4530pm' },
  { trail: TRAIL_NAMES.warrenGulch, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.cubCreek, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.goldenGateMuleDeer, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.marylandMountain, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.threeSisters, startTime: '5:45pm' },
  { trail: TRAIL_NAMES.virginiaCanyon, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.goldenGateMountainLion, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.floydHill, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.whiteRanch, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.marylandMountain, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.lairOfTheBear, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.virginiaCanyon, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.chimPex, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.deerCreekCanyon, startTime: '5:30pm' },
  { trail: TRAIL_NAMES.dakotaRidge, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.floydHill, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.whiteRanch, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.apex, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.threeSisters, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.lairOfTheBear, startTime: '5:00pm' },
  { trail: TRAIL_NAMES.greenMountain, startTime: '5:30pm' },
];
